### PR TITLE
fix(auth): Fix HuggingFace gated model auth for pyannote diarization

### PR DESCRIPTION
**Pull request by inductiontrace**
## Summary
- Transcription failed with `'NoneType' object has no attribute 'to'` due to pyannote gated model access denial
- **hf_hub_download patch**: WhisperX 3.7.0 passes removed `use_auth_token` param to newer `huggingface_hub`. Translates to new `token` param.
- **huggingface_hub.login() on worker init**: Gated pyannote models need more than just `HF_TOKEN` env var — `login()` registers the token and accepts gated terms.
- **AttributeError detection**: When gated access fails, pyannote returns `None` instead of raising. The `.to(device)` call on `None` gives an unhelpful error. Now detected and replaced with a message telling the user how to fix their HF token setup.

## Test plan
- [ ] Upload an audio file and verify transcription completes with diarization
- [ ] Set an invalid HUGGINGFACE_TOKEN, restart worker, upload file — verify UI shows clear gated model instructions

### CODE REVIEW

**Comment by davidamacey** [comment]
@inductiontrace Thank you for your pull request.  I am doing my best to keep up with the changes in the packages.

I will most likely not merge this PR, as I am working on Version 0.4.0 release with signification upgrades to OpenTranscribe.  I am in the midst of testing with a release pending soon!

Thank you again for your interest in OpenTranscribe!
